# Generated by Django 4.2 on 2023-04-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=25)),
                ('emailId', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=50)),
                ('conformPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
